### ISSUE TITLE
set JAVA_OPTS

### ISSUE THREAD

**Issue by kostyrev** [inkatze/wildfly#18]
Hello! I need to pass a bunch of JAVA_OPTS
e.g.
```
JAVA_OPTS="$JAVA_OPTS -XX:+UseThreadPriorities "
JAVA_OPTS="$JAVA_OPTS -Djboss.remoting.pooled-buffers=false"
```
and such to wildfly.
Usually my team injects those to `{{ wildfly_dir }}/bin/standalone.conf`
But this is not possible using this role 'cause it does not manage template for that file.
What be a good solution to this problem?
I'm thinking about adding a task to solve this but what would be a best option?
I could add template for {{ wildfly_dir }} /bin/standalone.conf or a `blockinfile` task 
What do you think?

**Comment by inkatze** [comment]
If you want to create a task to support a standalone.conf template that would be ok. Actually I'm ok with most additions as long as they're retro-compatible (ideally).

I also notice you added some more PRs; I have some free time today so I think I can review some of them, please be patient and thank you very much for your additions :)

**Comment by kostyrev** [comment]
Yeah.. I've added a lots of stuff.
But they all are backward-compatible and all the logic runs through feature toggles.
I also added molecule for CI but for some reason molecule itself is broken on Travis. It runs OK on my machine. I'll investigate it in a while.
You can install molecule [like this](https://github.com/kostyrevaa/workstation/blob/master/plays/molecule.yml) and test it for yourself. It's very convenient instrument.

**Comment by kostyrev** [comment]
But still.
How do **you** pass JAVA_OPTS to your wildfly?

**Comment by inkatze** [comment]
I'm not sure if this is what you are referring to since I'm not very Java savvy but I think I'd use [wildfly.conf.j2](https://github.com/inkatze/wildfly/blob/master/templates/wildfly.conf.j2) to add `JAVA_OPTS`, and things like `jboss.remoting.pooled-buffers=false` in [wildfly.properties.j2](https://github.com/inkatze/wildfly/blob/master/templates/wildfly.properties.j2). But as #16 describes, the systemd script doesn't support those files and those files don't support user supplied options at the moment.

**Comment by kostyrev** [comment]
I don't care for CentOS7 and systemd so the hell with it)
I found a workaround using task with `blockinfile` outside of the role and that will do for my use-case.
So I'm closing this issue.
