### ISSUE TITLE
Accept user supplied JAVA_OPTS and wildfly properties

### ISSUE THREAD

**Issue by inkatze** [inkatze/wildfly#19]
[wildfly.conf.j2](https://github.com/inkatze/wildfly/blob/master/templates/wildfly.conf.j2) and [wildfly.properties.j2](https://github.com/inkatze/wildfly/blob/master/templates/wildfly.properties.j2) can only manage a very specific subset of the available options. The idea was letting the user edit those files to add more options to those files, but it's a better idea to manage those options with variables.

**Comment by juhoffma** [comment]
This is also possible via the shipped start scripts, isn't it? If the scripts find a JAVA_OPTS env variable, it will consider it... see [standalone.sh](https://github.com/wildfly/wildfly-core/blob/5ff6433a5f06051ce8c29c654e9957d463e9ce77/core-feature-pack/src/main/resources/content/bin/standalone.sh#L277)

**Comment by inkatze** [comment]
That's correct, but there're some use cases in where is not possible to set env vars and/or is more practical to have them as a role variable. I just want both options to be available for that reason.

**Comment by onitake** [comment]
This is a feature I'd like to see as well.
We have a specific use case where there's no clean way to add additional properties other than adding them to wildfly.properties.

I suggest adding two new (optional) variables that hold a list of key:value pairs, which are then rendered into wildfly.properties and wildfly.conf, respectively.
Since environment variables and properties are unique, it would even make sense to use dictionaries for these lists.

Example:
```yaml
wildfly_custom_properties:
  key1: value1
  key2: value2
wildfly_custom_environment:
  CUSTOM_ENV: value
```

Rendering could be done like this:
```jinja2
{% for key, value in (wildfly_custom_properties | default({})).iteritems() %}
{{ key }}={{ value }}
{% endfor %}
```

**Comment by kostyrev** [comment]
PRs are welcomed

**Comment by onitake** [comment]
Here you go, please review.
